/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_JTest */

#ifndef _Included_com_jni_JTest
#define _Included_com_jni_JTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_JTest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_JTest_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
